### ISSUE TITLE
How to get the dataset?

### ISSUE THREAD

**Issue by MengzhangLI** [sgadgil6/cnslab_fmri#2]
Hi, thanks for sharing your excellent work of MICCAI 2020.

I want to re-implement this project, but I don't know how to get the data used in paper. 

Will you share or plan to share the data related with this paper?

Thank you!

**Comment by sgadgil6** [comment]
Hello,
For HCP, you should be able to download the data "Resting State fMRI 1 Preprocessed" from https://db.humanconnectome.org/. The GIFTI images were then parcellated using https://balsa.wustl.edu/QnXj

Here are the final processed BOLD signal files: https://drive.google.com/file/d/1c4UYvp089KwqAllAHdHMHGjq8y5x882D/view. I will add that to the README. 

If you need the NCANDA data, you should directly contact last author Dr. Kilian Pohl (kilian.pohl@stanford.edu) for data usage.

**Comment by MengzhangLI** [comment]
> Hello,
> For HCP, you should be able to download the data "Resting State fMRI 1 Preprocessed" from https://db.humanconnectome.org/. The GIFTI images were then parcellated using https://balsa.wustl.edu/QnXj
> 
> Here are the final processed BOLD signal files: https://drive.google.com/file/d/1c4UYvp089KwqAllAHdHMHGjq8y5x882D/view. I will add that to the README.
> 
> If you need the NCANDA data, you should directly contact last author Dr. Kilian Pohl ([kilian.pohl@stanford.edu](mailto:kilian.pohl@stanford.edu)) for data usage.

Hi, Soham:
Thanks for your nice reply, can't wait to re-implement this project.

Best,

**Comment by MengzhangLI** [comment]
> Hello,
> For HCP, you should be able to download the data "Resting State fMRI 1 Preprocessed" from https://db.humanconnectome.org/. The GIFTI images were then parcellated using https://balsa.wustl.edu/QnXj
> 
> Here are the final processed BOLD signal files: https://drive.google.com/file/d/1c4UYvp089KwqAllAHdHMHGjq8y5x882D/view. I will add that to the README.
> 
> If you need the NCANDA data, you should directly contact last author Dr. Kilian Pohl ([kilian.pohl@stanford.edu](mailto:kilian.pohl@stanford.edu)) for data usage.

Hi Soham:
I download HCP data from this google drive. It is a folder with 1096 cases each of them is a numpy array (22* 1200 just as your paper shows).
However, in your code it is:

train_data = np.load('data/train_data_1200_1.npy')
train_label = np.load('data/train_label_1200_1.npy')
test_data = np.load('data/test_data_1200_1.npy')
test_label = np.load('data/test_label_1200_1.npy') 

What should I do if I want to run your model on HCP data？

Best, 

Mengzhang Li

**Comment by MengzhangLI** [comment]
Sorry for my questions.

I forgot to see "preprocessing.py".
